version: '3'

services:
  dbpostgres:
    container_name: ${POSTGRES_DB_NAME_SERVICE}
    image: postgres:12.17-alpine3.19
    volumes:
      - xperia-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    restart: always

  node_server:
    depends_on:
      - dbpostgres
    container_name: ${XPERIA_SERVER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3005:3005

volumes:
  xperia-vol:
    external: false

networks:
  postgres:
    driver: bridge
